--Previewing the data
select * from customer limit 20; 

--Now we have to answer certain business ques.


--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;




--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount  
from customer
where discount_applied = 'Yes' 
		and purchase_amount >= (select avg(purchase_amount) from customer);



-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2)  as avg_product_rating
from customer 
group by item_purchased
order by avg_product_rating desc
limit 5;




--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount::numeric),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;




--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
		count(customer_id) as total_customers,
		round(avg(purchase_amount::numeric),2) as avg_spend,
		sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue;



--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(SUM(
		CASE
			WHEN discount_applied = 'Yes' THEN 1
			ELSE 0
		END )*100/count(*),
		2) as percent_bought_when_discount
from customer
group by item_purchased
order by percent_bought_when_discount desc
limit 5; 




--Q7.** Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
-- once = new, 2-10 : returning, >10 : loyal

with customer_segment_cte as
(
	select customer_id, previous_purchases,
	 CASE
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		WHEN   previous_purchases > 10 THEN 'Loyal'
	END as customer_segment
	from customer
)
select customer_segment, count(*)
from customer_segment_cte
group by customer_segment;




--Q8. What are the top 3 most purchased products within each category? 
with most_purchased_cte as(
	select category, item_purchased, 
		count(customer_id) as total_orders,
		row_number() over(partition by category order by count(customer_id) desc) as item_rank 
	from customer
	group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from most_purchased_cte
where item_rank <=3;




--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;


 

--Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc; 




-- exporting tehe table





